### ISSUE TITLE
Allow selecting ssh key out of multiple when using -u

### ISSUE THREAD

**Issue by lipanski** [ssh-vault/ssh-vault#1]
I have multiple SSH keys set up on Github. When encrypting a message and using the `-u` option, it would be nice to be prompted about which key to use to encrypt the message.

thanks!

**Comment by nbari** [comment]
hi @lipanski many thanks for catching this out.

I came with this approach, for been available specify a key, when using the  ``-u <username>`` option the ``-k N`` can be used, in where N is the index to use, for example if User Bob wants to send something to user Alice but using her second key, this could be used:

    $ ssh-vault -u alice -k 2 create vault

Would be nice if you give a try, some binaries/docs for this release can be found here: https://ssh-vault.com/

**Comment by lipanski** [comment]
thanks! I will try it out :balloon:
