### ISSUE TITLE
"exec: "ssh-keygen": executable file not found in %PATH%"

### ISSUE THREAD

**Issue by nbari** [ssh-vault/ssh-vault#11]
Windows having this issue while trying to open/view a vault:

    "exec: "ssh-keygen": executable file not found in %PATH%"

**Comment by bbogdanov** [comment]
ssh-keygen is part of Git. If you reinstall the git with checking the Unix tools for windows command prompt radio button all will go fine.

**Comment by nbari** [comment]
hi @bbogdanov  thanks for the hint.
