### ISSUE TITLE
Decryption failed, use private key with fingerprint: 

### ISSUE THREAD

**Issue by nbari** [ssh-vault/ssh-vault#14]
when trying to view the content of a vault, if the key doesn't match, prints the default  key on the system:

```
$ ssh-vault view vault.ssh 
Decryption failed, use private key with fingerprint: fd:c9:a5:ab:67:c2:6a:3b:6b:c9:72:d6:32:f8:a8:09
```

**Comment by Shadowys** [comment]
Same problem here. Using Ubuntu on windows, ssh-vault copied to /usr/local/bin

**Comment by nbari** [comment]
@Shadowys you need to use the private key of the user you used to encrypt, for example the following vault was created for you using your keys (https://github.com/shadowys.keys): 

```
SSH-VAULT;AES256;e4:f2:b3:c7:b5:fc:90:d7:ad:a0:b2:88:1b:8f:b8:d6
MmYYdxiK7dipuJTd0JdnoyMtOj90AVeX2BLJ5BeNTVjB62vHd1sdmfhwqnt/zMfR
zy0eyc1fM3VSjBHmcvNX/eiwh0YR0UbX4eEXGrr8urewhVkpkY+lF0Qs5Wd/L01t
ucnd5pMPRmNxZitbB3YDd/RILB0U6yXMl7dtNdN7cMGVYKjcT547KR3kePfjkXWk
DVHfHLNMJZYjiCRCzp5A6SmGTJYa7Txg4pzbqNHG+uzmD6qtnGZ242iKJYaMYDuR
8AU4R2hlbarShZFu+bDiHTC0zuQHBcnxGQ0iUUUryg7dVgwlCFL2Jv90RzZb7hW1
cJfqGSkkuaydYEEc2S2idw==;x8VPc4T9T1sSIdFFHfldZiqWM0eRXaWINxr/nbW
4PIsQGfXEBt6WVK1Ta1oQBUB6YAslZAeugAjHedKGoqkOthlrjkzSNbH/yJgamk1
j/deazJVSErS6dXOf8ANX8b9uzXgH3cmothlSUCyq6A==
```

So in order to decrypt the file you should specify the private key for you keys, something like this:

    ssh-vault -k /path/to/key view vault # vault is the data above

**Comment by nbari** [comment]
@Shadowys please update to `0.8.2` should print not the fingerprint of the key to use

could you please test and let me know if is working from your side?

**Comment by Shadowys** [comment]
I don't think it's working. Can you show me an asciicinema of how you did it?

**Comment by nbari** [comment]
Hi, can you describe exactly what you are doing ? meantime hope this helps: https://asciinema.org/a/105690

Remember that for been available to decrypt something you need to be the owner/have access to the private keys.

In case getting an error could you please show it also describing the steps.

regards

**Comment by nbari** [comment]
@Shadowys any news on this?

got it working from your side?

Maybe could be better to create/view not piping data, example:

    ssh-vault create vault test.ssh
    # and editor will be opened 

And to view contents:

    ssh-vault view test.ssh

depending on the key used to encrypt the vault it may ask for entering your password.

let me know if how it goes.

**Comment by Shadowys** [comment]
I got it working 
`ssh-vault create vault test.ssh`
and then to view,
`ssh-vault view vault test.ssh`

thanks!
