### ISSUE TITLE
allow creating secrets to STDOUT (without writing to file)

### ISSUE THREAD

**Issue by lipanski** [ssh-vault/ssh-vault#15]
hey

first of all, thanks for the awesome tool :pizza: 
would it be possible to allow creating secrets on the fly, straight to STDOUT (without having to write to file)?

something like `ssh-vault -u nbari create` and, if no file parameter is specified at the end, just open the editor and print the encrypted message to `STDOUT`.

**Comment by nbari** [comment]
@lipanski many thanks for the feedback.

Plese try latest version `9.0.0` it should allow you to create vaults on the fly like you suggested, example:

    echo "secret" | ssh-vault -u lipanski create 

To copy the output you could also do a one-liner:

    echo "secret" | ssh-vault -u lipanski create | pbcopy

Please give a try and let me know if is working from your side.

**Comment by lipanski** [comment]
works! thanks.

how about allowing to decrypt messages from `STDIN`? (so we won't need files at all)

someth like `echo "encrypted stuff" | ssh-vault view`?

**Comment by nbari** [comment]
@lipanski  please give a try to `0.9.1` should be capable of doing that, example:

    echo "secret" | ssh-vault -u lipanski create | ssh-vault view

**Comment by lipanski** [comment]
:star: :star: :star: :star: :star:
