### ISSUE TITLE
support choosing keys using their fingerprint

### ISSUE THREAD

**Issue by mpomm** [ssh-vault/ssh-vault#19]
Given the case that i want to use ssh-vault in a automated way and that the user i want to encrypt for has more than one key.

In the moment i have to choose the key using his place in the line in github e.g.: 
```
ssh-vault -u user -k 2 create
```
this implementation is bounding the keyholder to always have this specific key at the second place in line in Github.
A more flexible and better to automate way doing this would be using the keys fingerprint instead the place in the line (in my example i use -f for fingerprint) e.g.:
```
ssh-vault -u user -f ab:cd:ef:gh:ij:kl:mn:op:qr:st:uv:wx:yz:01:23:45 create
```

**Comment by nbari** [comment]
Hi @mpomm, nice catch, please check version 0.11.0, should be capable of achieving this.

Please test and let me know if is working as expected.
