### ISSUE TITLE
HOME environment variable ignored 

### ISSUE THREAD

**Issue by nbari** [ssh-vault/ssh-vault#24]
HOME environment variable.

https://github.com/Homebrew/homebrew-core/pull/18238#issuecomment-333303163

Ideally a defined `CACHE_DIR` could be defined, if not found try to use the `$HOME` environment if is different from the output of `usr.HomeDir`

**Comment by nbari** [comment]
Fixed in 0.12.3 but need better testing

**Comment by RowanAJMarshall** [comment]
Can you reiterate what there is to do? Regression testing for the HOME env variable?

**Comment by nbari** [comment]
Hi @RowanAJMarshall,  yes, that would be helpful
