### ISSUE TITLE
Provide signature functionality

### ISSUE THREAD

**Issue by elyscape** [ssh-vault/ssh-vault#25]
It would be nice if ssh-vault could be used to generate and verify signatures. It would be necessary to generate a SHA-2 hash of the content first.

**Comment by nbari** [comment]
Hi @elyscape could you please give me an example? currently the option `-f` creates the fingerprint but don't know if that is what you mean, for example: 

    $ ssh-vault -u elyscape -f
    85:b6:40:92:af:c4:5f:1b:bd:2f:24:22:2f:e6:bf:a3

for the second key:

    $ ssh-vault -u elyscape -f -k 2
    88:dd:91:3d:9d:41:d0:25:19:4a:a1:65:ce:5b:31:a2
