### ISSUE TITLE
allow for encryption to multiple recipients

### ISSUE THREAD

**Issue by S2-** [ssh-vault/ssh-vault#26]
It would be nice if the -u option could be repeated, to allow multiple recipients. Something like
```
ssh-vault -u id_rsa-1.pub -u id_rsa-2.pub -u id_rsa-3.pub create vault.ssh
```

**Comment by nbari** [comment]
That is a little complex, check this: https://ssh-vault.com/post/group-encryption/

**Comment by nbari** [comment]
you could probably do something like this:

```
usrs=('user1'  'user2'  'user3')
for i in $usrs; do
echo "secret" | ssh-vault -u $i create $i.vault
done
```

**Comment by S2-** [comment]
thank you @nbari, in the meantime I made a bash script that does the same, and allows encryption for multiple recipients. https://github.com/S2-/sshencdec

**Comment by nbari** [comment]
greate, for now, I will close the issue, please feel free to open it if required.

Regards.
