### ISSUE TITLE
create tests

### ISSUE THREAD

**Issue by nbari** [ssh-vault/ssh-vault#3]
Protect still on a very early stage, but some test could help to start cleaning, improving the code.

**Comment by IngCr3at1on** [comment]
@nbari mind if I take a crack at this?

**Comment by nbari** [comment]
Sure, please,  I just submit some changes to have at least the 3 options ``edit``, ``view``, ``create`` to work

**Comment by nbari** [comment]
Please push to branch develop

**Comment by IngCr3at1on** [comment]
@nbari for my own reasons I always push to a feature branch on my repos but I changed the PR to have it merged to develop instead of master.

**Comment by nbari** [comment]
Thanks for the tests, could be nice to try to improve the coverage

**Comment by IngCr3at1on** [comment]
@nbari I was thinking about that but I think you'll have to modify your codebase a bit to allow for that.

**Comment by nbari** [comment]
@IngCr3at1on you are right, any suggestions are welcome
