### ISSUE TITLE
Group functionality improvements

### ISSUE THREAD

**Issue by boxrick** [ssh-vault/ssh-vault#30]
Do you have any plans to support any group functionality rather than distributing a single shared key? As it stands the functionality is 99% of the way there to mean I never need to touch GPG but without multiple users renders things a little useless.

**Comment by nbari** [comment]
Hi @boxrick like specified [here ssh-vault](https://ssh-vault.com/post/group-encryption/) is not properly designed for group/broadcast encryption, but contributions or ideas about how could this be implemented are always more than welcome

**Comment by pinpox** [comment]
This feature would be great and would make ssh-vault extremely useful. 

Looking at the the ["How it works"](https://ssh-vault.com/post/how-it-works/) documentation, the obvious solution to this would be to encrypt the randomly generated key multiple times, with each of the recipients public keys. You probably have already most of the necessary code.

This approach is what https://github.com/mozilla/sops sops does. For example let's say I want to create a vault that is both readable by alice and bob, the procedure would be:

Encryption:
1. Generate random key 
2. Encrypt data with random key
3. Encrypt random key with alice's key
4. Encrypt random key with bob's key
5. Add encrypted data to message
6. Add alice-encryped random key to message
7. Add bob-encrypted random key to message

For decryption bob would decrypt the copy of the random key encrypted with his key and decrypt the message with the plaintext random key.

This would allow to use `ssh-vault` in arbitrary large teams. A possible interface would be to allow to specify multiple `-k` keys.
