### ISSUE TITLE
Missing vault name, use ("ssh-vault -h") for help.

### ISSUE THREAD

**Issue by faxotherapy** [ssh-vault/ssh-vault#35]
Hello,

I'd like to add a bunch of PDF files to an **existing** vault. I tried different ways, but none of them work.
```shell
$ cat *.pdf | ssh-vault -k ~/.ssh/id_rsa.pub edit vault.ssh
$ cat *.pdf | ssh-vault -k ~/.ssh/id_rsa.pub edit -o vault.ssh
$ cat *.pdf | ssh-vault -k ~/.ssh/id_rsa.pub -o vault.ssh
$ cat *.pdf | ssh-vault -k ~/.ssh/id_rsa.pub vault.ssh
```
I don't seem to figure out how to do this after reading the man page.

Just realised how would I access the PDF files in the vault? Should the vault be plain text only instead so we cant access its content using the `view` option only?

I was mislead by your example:
```
cat file | ssh-vault -u bob create vault
```

I guess file is text only. So, I can't add any file.

Thanks for your help.

**Comment by nbari** [comment]
If you would like to add a pdf you could so something like:

    $ ssh-vault create < your.pdf > your.pdf.ssh

Then for `decyrpt` the content you could use something like:

    $ ssh-vault -o my.pdf view your.pdf.ssh

Now if you have multiple files yould create a `tar` and then encrypt it, for example:

    $ tar -Jcf your-pdf-files.tar.xz your-pdf-files
    $ ssh-vault create < your-pdf-files.tar.xz > my-pdf-files.ssh

To decrypt, same as before:

    $ ssh-vault -o /tmp/restore/here.tar.xz view my-pdf-files.ssh
    $ cd /tmp/restore
    $ tar -Jxf here.tar.xz

If you are using your own key, no need to use option `-k` sinde defaults to `~/.ssh/id_rsa.pub`

Also notice that the `edit` option is more for `text/json/yaml` files something that you may want to use with something like `direnv`, check this issue to get more ideas: https://github.com/direnv/direnv/issues/320
