### ISSUE TITLE
No valid PEM (private key) data found

### ISSUE THREAD

**Issue by faxotherapy** [ssh-vault/ssh-vault#36]
Hello,

I use the public key of some friend to encrypt some content:
```
ssh-vault -k ~/.ssh/vault/keys/id_rsa.pub create < QR.jpg > RQ
```

From the friend's computer:
```
ssh-vault -o QR.jpg view RQ
```

Unfortunately, he's got the message *No valid PEM (private key) data found*

He's got well his private key in `~/.ssh/id_rsa`

Thanks for your help.

**Comment by faxotherapy** [comment]
I found the problem.

- When I use `ssh-keygen` from `/usr/bin/` folder I have no problem at all.
- When I use `ssh-keygen` from `/usr/local/bin/` folder the issue appears.

I don't understand why I cannot use the binary from `/usr/local/bin/`

Strange!

**Comment by nbari** [comment]
@faxotherapy try to add first in your path the version that works, for example:

     export PATH="/usr/local/bin:/usr/bin:$PATH"

I would later check versions, etc, to see what could be the problem.

**Comment by gkruszecki** [comment]
I have the same problem. In my case it's related with new private key format used by default by openssh >= 7.8

```
 * ssh-keygen(1): write OpenSSH format private keys by default
   instead of using OpenSSL's PEM format. The OpenSSH format,
   supported in OpenSSH releases since 2014 and described in the
   PROTOCOL.key file in the source distribution, offers substantially
   better protection against offline password guessing and supports
   key comments in private keys. If necessary, it is possible to write
   old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
   when generating or updating a key.
```
block.type in this case looks like "OPENSSH PRIVATE KEY" not "RSA PRIVATE KEY"

**Comment by nbari** [comment]
@gkruszecki currently only RSA keys are supported, give a try with an RSA key and if required feel free to create an issue.

**Comment by gkruszecki** [comment]
@nbari. The funny thing is that these are RSA keys but written in new OPENSSH format not PEM.
A public part looks the same. Only a private key is written in a different format.
Since version 7.8/7.8p1 (2018-08-24) ssh-keygen  by default generates RSA keys in new format and they don't work with ssh-vault any more

**Comment by nbari** [comment]
@gkruszecki please create another issue for this topic, (probably can be fixed here https://github.com/ssh-vault/ssh2pem/blob/master/ssh2pem.go#L121)
