### ISSUE TITLE
Review homebrew formula

### ISSUE THREAD

**Issue by iwittkau** [ssh-vault/ssh-vault#38]
Hi, the ssh-vault homebrew formula is currently blocking a pull request to update the go formula to 1.13.5. Details here: https://github.com/Homebrew/homebrew-core/pull/47510#issuecomment-565634744

Can someone take a look at why [the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ssh-vault.rb) fails on macOS with go 1.13.5, please?

**Comment by nbari** [comment]
Hi @iwittkau formula has been fixed PR here: https://github.com/Homebrew/homebrew-core/pull/47847 but wondering if there is another way of doing this changes by using `brew` itself

**Comment by iwittkau** [comment]
@nbari thank you for your quick action! I don't think there is a another way to fix a formula other than providing a pull request with a fix. 
Thanks again!

**Comment by iwittkau** [comment]
Unfortunately there is a build error, reproduced on my local machine:

```
$ git checkout 0.12.4
$ dep ensure -vendor-only
$ make
go get
# github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/go-keychain
vendor/github.com/ssh-vault/go-keychain/corefoundation_1.10.go:55:26: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFDataCreate
vendor/github.com/ssh-vault/go-keychain/corefoundation_1.10.go:81:47: cannot use nil as type _Ctype_CFAllocatorRef in assignment
vendor/github.com/ssh-vault/go-keychain/corefoundation_1.10.go:118:34: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithBytes
vendor/github.com/ssh-vault/go-keychain/corefoundation_1.10.go:153:39: cannot use nil as type _Ctype_CFAllocatorRef in assignment
make: *** [get] Error 2
```

It works in master, can you release a new version and also bump it in your PR?

**Comment by nbari** [comment]
hi @iwittkau thanks for checking this, I created a new tag `0.12.5` with the updated dependencies, but wondering how to update now the formula using `brew`, I was thinking on using `brew bump-formula-pr` but that will create a new PR?

**Comment by iwittkau** [comment]
Thanks, @nbari! I don't know what's the recommended way to do this. Submitting a PR manually worked for me.

**Comment by nbari** [comment]
https://github.com/Homebrew/homebrew-core/pull/47510#issuecomment-565757413, https://github.com/Homebrew/homebrew-core/commit/2ab4af102dd04bad9337401b161f849783fc59bb
