### ISSUE TITLE
RSA key in openssh format with password

### ISSUE THREAD

**Issue by CyrilJacob** [ssh-vault/ssh-vault#44]
Hello,
Two issues I wanted to report (I believe related to #37) that I have recently experienced on my mac (catalina) when using ssh-vault:

- First issue

**_how to reproduce the issue:_**
`ssh-keygen -t rsa -b 4096 -C "email@example.com" `([gitlab example](https://docs.gitlab.com/ee/ssh/README.html#generating-a-new-ssh-key-pair))
`ssh-vault -k id_rsa.pub create < file > file.vault`
`ssh-vault -k id_rsa view file.vault`

**_output:_**
enter passphrase:
could not parse private key: ssh: this private key is passphrase protected

**_analysis:_**
When having a passphrase protected key, and no usual PEM header (no dek-info section as tested by x509.IsEncryptedPEMBlock()), it goes through  ssh.ParseRawPrivateKey() instead of ssh.ParseRawPrivateKeyWithPassphrase().

However without password it works fine since it goes through ssh.ParseRawPrivateKey and when -k parameter is the private key ssh-keygen -yf works, if -k is a public key it works too (when both are in local and in the same directory).

_**proposal:**_
Either decode the header of the openSSH format private key that should contain something like this when encrypted:
> openssh-key-v1
> aes256-ctr bcrypt

Or when having a block.Type of "OPENSSH PRIVATE KEY" trying ssh.ParseRawPrivateKey() followed by 
ssh.ParseRawPrivateKeyWithPassphrase() when the first is not successful.

- Second issue

Also a second issue appears due to -k parameter. Indeed the usage of ssh-keygen -yf  doesn't deal well with passphrase protection. So it works when having the public key as parameter but not the private one. (when both are in local and in the same directory).

**_how to reproduce the issue:_**
`ssh-keygen -t rsa -b 4096 -C "email@example.com" -m PEM `([gitlab example]

**_analysis:_**
I don't know why we need to extract sometimes the public key from the private one.  -k parameter as showed by the command helper is a public key so I am not quite sure why we are passing the private key sometimes even though that is the private key which is needed to decrypt. 

```
	// use private key only
	if strings.HasSuffix(v.key, ".pub") {
		v.key = strings.Trim(v.key, ".pub")
	}
```

_**proposal:**_
Either decoding the private key and the public from it without using ssh-keygen as already mentionned in the TODO or perhaps adding another parameter to distinguish between public and private keys. Another option could also be to add the suffix pub and get it.

Thanks for the great work and your help !

**Comment by nbari** [comment]
Hi  @CyrilJacob thanks for checking this, will do some further testing 👍

**Comment by nbari** [comment]
I key is `OPENSSH PRIVATE KEY` it needs to be converted to pem with something like:

    ssh-keygen -p -P  "your passphrase " -N "your new passphrase" -m pem -f id_rsa

> `chmod 700` id_rsa

**Comment by nbari** [comment]
https://github.com/ssh-vault/ssh-vault/pull/50
