### ISSUE TITLE
could not parse private key ssh: this private key is passphrase protected

### ISSUE THREAD

**Issue by bsutton** [ssh-vault/ssh-vault#45]
I'm running on ubuntu trying to decrypt a file:

```
cat vault/encrypted | ./ssh-vault view
could not parse private key: ssh: this private key is passphrase protected
```

Looking at some of the code it looks like it should prompt for the pass phrase or pull it from the key chain.

Any reason why it appears to be doing neither?

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

```
```
./ssh-vault -v
0.12.6
```

**Comment by nbari** [comment]
The problem is that you are sending  the "vault" via `stdin`, `ssh-vault` prompts for the password but uses the input (the encyrpted data) and therefore returns with the error, in this cases first write the vault to a file and then use something like:

     ssh-vault view /path/to/file.ssh

unless your keys are not passphrase protected you could then pipe the file and it will work

**Comment by bsutton** [comment]
Ok.
I was trying to avoid writing the data to disk hence the use of stdin.
Could this be changed so you can pass the data or the password via an environment var (not ideal as some OS allow you to see environment vars) but better than writing to a file.

**Comment by nbari** [comment]
If you would like to automate something the easiest way, for now, could be to use ssh-keys without a passphrase.

The idea of buffering all the input `stdin` and then prompt for the password only if required probably could be done, I agree that in some cases is nice not needing to write the file on disk, ane even better when you don't have to type the password and use your ssh-agent for it like it was possible in some versions of macOs: https://github.com/ssh-vault/ssh-vault/issues/31

**Comment by nbari** [comment]
Hi @bsutton option `-p` should fix this: https://github.com/ssh-vault/ssh-vault/issues/54#issuecomment-1809065509

**Comment by bsutton** [comment]
thanks.
