### ISSUE TITLE
bad ssh-vault signature

### ISSUE THREAD

**Issue by bsutton** [ssh-vault/ssh-vault#46]
I'm encrypting a file using ssh-vault via:

```
 cat test/data/note_to_encrypt.txt | ./ssh-vault -u bsutton create ./test.vault
```
This produces a file:
```
SSH-VAULT;AES256;ee:88:c8:35:4d:0e:a9:14:c1:44:61:59:90:95:ef:a0
GxjmmbzD0yR4m0WAdeEOQqViVfaq/KMrEV3bUVZAT/bTT/JuJeg5mXwHMm3DED1y
SW44D3HZg8jKWeIKms0zsy0p273jCZ+Wi/gj5lTGzsQaltPTpgiX36N9RY9z2eSh
N/+RPvU8NVfMLE1YvhjBqz+Vnz9iFhivG46TwKKihUUyAt7NmCDIxn6KRNDvGeUF
YSWwQwXCuqLcO1mE12YkLA6TzoH9cXm+9jU39Bh8VTPqDW4teTcfXgGP7s2f3M1N
qh1u4IASW58XkpOI5A0OufrvWfpwWhkLKWNtPpPkeBXYvuH2faeCVHVxHcQ+p62+
bk09zczek3GyrW23AV60f24tNo/EDjUqJ6PEvIHTWrpEZEORC2rYAX/YgDUrG2Jw
WuVWOsfN+E/QMs+vvdJw7zvKiy/jA3NGUJWhES3DneKanV0SVKlOmoRDQehKtU6X
0lb5c6nQB4z/cI8uP7bhIE4WTFv2u/VXnHYIIssjM4aZWHs/TkZzeLEQHldadIhm
or/pF0hG606PunAyeGDO3nHuzyT45DJ+ywmGXln+y+QALjjvMllI9lnwR99o6/ZD
gXuyhSwaqHCWOLwaTFZ4IK2kdE7shWKlKYnyqldPlV6NBzouuTcWu4EgNGv0MNLm
DwdwWc8AqgT2fTvfHyILx4GfDVXgqe/BpwL/MTLK3u0=;bLlYIF+UyrlG8zrWTAo
FH5h/RQ/WgrZ7gfZgNrQF/ZOUusJaq8Ho6TJ5p429avPwPbaAumFSX+DwwWCDcWw
Y2peF9tvqaOgiy8MJkDAf9OB4L/6WWSBbsqiyViJlGXGhzA==
```

When I try to decrypt the vault I get:

```
echo "<pass phrase>" | ./ssh-vault  -k /home/bsutton/.ssh/id_rsa view test.vault
bad ssh-vault signature, verify the input
```

The private key file is encrypted with <pass phrase>

As I understand it you can pass the passphase phrase via stdin hence I pipe the output from the echo command.

However I'm seeing two problems.
1) the above invalid signature
2) even though I pass the passphrase the command is using the gnome agent to request I enter the pass phrase.

I'm uncertain if these two problems are related?

**Comment by nbari** [comment]
You need to use the public key not the private key, try with **id_rsa.pub**

    ./ssh-vault  -k /home/bsutton/.ssh/id_rsa.pub view test.vault

**Comment by bsutton** [comment]
OK, so I'm confused.
This document says otherwise:
https://ssh-vault.com/post/how-it-works/

I was expecting to be able to encrypt any file using the public key and the do the decryption using the private key.
This allows encryption to occur without having to unlock the privatekey (with the pass phrase). 
The other way around is much less useful.
I was expecting to be able to have automated processes encrypt data for safe keeping and only need a human involved (with the private key phrase) when decryption was necessary.

In an alice/bob world, alice encrypts with bobs public key and bob decrypts with his private key. So I expected ssh vault to work the same way and the above noted doco appears to agree?

**Comment by nbari** [comment]
You encrypt using the **public** key and then decrypt using the **private** key.

By default  **public** key `~/.ssh/id_rsa.pub` is used and therefore the **private** `~/.ssh/id_rsa`  is used,  you may have multiple *vaults* with different keys so then you could use something like `-k ~/.ssh/id_devops_rsa.pub` and the private key to be used will be `~/.ssh/id_devops.rsa`

So to simplify things if you just need to encrypt/decrypt something for you using the default (`id_rsa`) without password/passphrase  key you can just do:

    echo "test" | ssh-vault create | ssh-vault view 

If your ssh keys have password/passphrase:

    echo "test" | ssh-vault create /tmp/vault.ssh

And to view the contents:

    ssh-vault view /tmp/vault.ssh


What are you trying to do?
