### ISSUE TITLE
Documentation unclear on use of -k and -u

### ISSUE THREAD

**Issue by bsutton** [ssh-vault/ssh-vault#47]
The documentation states that you can pass a `-u` flag to nominate a github username.

Its not clear what this actually means.

Is this searching the ~/.ssh directory for a key file with the given name?
What files does it search?

What file does the command use if I don't pass the `-u` flag?

What is the difference between using and not using the `-u` flag?

The doco states that the `-k` flag can be used to specify the key file in conjunction with the `-u`. 

Can the -k flag be used to specify the key file even when the `-u` flag isn't used?

The doco is rather thin, some additional documentation would be greatly appreciated.

**Comment by nbari** [comment]
from `ssh-vault -h`: 

```
$ ssh-vault -h
Usage: ssh-vault [-f fingerprint] [-k key] [-o file] [-u user] [create|edit|view] vault

...
  -u username or URL
        GitHub username or URL, optional [-k N] where N is the key index to use, example:
                    ssh-vault -u <user> create      # Using first key found in github.com/<user>.keys
                    ssh-vault -u <user> -k 2 create # Using second key
 ```

And to complement, hopefully, this can help: https://ssh-vault.com/post/u-option/.


For example, if I want to send something to you but using your [2 key in github](https://github.com/bsutton.keys) I would do something like:

      $ echo "help me to improve the docs" | ssh-vault -u bsutton -k 2 create

It will output something like this:

```
SSH-VAULT;AES256;ee:ab:25:92:b2:b2:25:a2:db:46:cd:dd:96:e0:f3:46
yupoObSRURRbufC5YpqngFBVmgAiBA73ZGIkR/2GJgggYXwtcrJ+L+NWcY97X8fP
Mj7o+j4G1rpqkAZ+QXO5O/cRwu4CjF2BGvNwHPDltdCTdzEX1B3q9b5j05bm6aJD
DbT+RjS13I7KQ320K7CQDuerhOafI6blU/rQykywAOVlLPuAdCI/VLylJQAITE8P
TvWSpLIRXv1sNPuS2at2WXab7R+kf64L4IFIzAfM/HYl6sSSnLjhRZia4jdUrbhu
sfYdjkTqZxSEeZS9SM5DifZujzM+HE6a5XEFHTCadBiIIWl7ydbIQ3XRj/xaX5sV
TrRXGvi0hcspa0KJ1CKej5R9E0XXpS5FGUM2G2wFM0GS/hhC23ul7Jh2GmkJyVDB
S0eB9xx8w9xVzto+SHGrKkheM+FUmzHekyHIY6KO8+HyapPM+fENPfr4d0k0aigW
U2ZegKqfB/lGtR6yZaDZvxm4LGeIpuDlAc4Wxd2j5ZcqIz1SE6AtSnkeG22bhn0f
;0ivFivzGhsGBrtH4o2rsCvBANfCcrLbyCahrE0gA4sOKk0RCgrDn74RHOs3BcXs
T9b80ZbNy2qM=
```

And you will have to open it with your second key:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD0/hSixVVDsEzXTel313GFE2wB7jt3iVeKkLYBN8hRIzTtMLr7TTdr73rHysU04Y9w770lIt4rZv8ZbIqxNt/dR2krked1kLyUxSUQaxdK6o01ZwEdGL6yKou353d2SwPsDAKsKwvLQlPuNAO1uJm6LcdegXY5u8zaGg+eplp0G/r8/ZNP7H93NX1UyLTBI/nj8mAAEfgkUeEa7cF4uIFxgTRUGu1SY5GJQF3Jp4VmZPn3yLaz2FdHZAB9Wu1wJXqN0ODkCqjhNtol/+akl4fu+XHnB9IjwCoyLFbqLg7JlI0EA/1kxjm/iWrdSBuFneHFxp5OUm7m4ANH2Z6VCV4X8ZqqfrmxBGEfgapK+Yvv473upy72KJhv95Z3D2yi+b1UaKSeMCIlUX6HuVXcU+mViVVVta2R47gPXVRxvFmBIu9EhGAxTo8yH3n9TuAOX4wze84BDdA+TltK6N1pLCndwo/NlPLY/uwqa9snVxEQppov1vRSZrMfpZM79RW7th0=
```
     

If still unclear please let me know and then let's work in improving the docs so that it could become easier for others.
