### ISSUE TITLE
Go module support

### ISSUE THREAD

**Issue by roopakv** [ssh-vault/ssh-vault#48]
This tool is installable via brew. in order to maintain go 1.17 support as well make maintenance easier could the maintainers please add go module support.

Homebrew/homebrew-core#47627

**Comment by nbari** [comment]
Hi @roopakv thanks I will check it out

**Comment by nbari** [comment]
Hi @roopakv I added go module support in the latest release https://github.com/ssh-vault/ssh-vault/releases/tag/0.12.7, could you please help to check if the brew formula is fine or if I need to do something?
