### ISSUE TITLE
Downloads Broken

### ISSUE THREAD

**Issue by iSynaptic** [ssh-vault/ssh-vault#49]
I'm no longer able to download binaries. I believe this is because Bintray has been sunset: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Would it be possible to publish binaries through Releases here on GitHub?

**Comment by nbari** [comment]
Hi @iSynaptic yes that could be an option, let me see how to build them (probably using a Github Action)

**Comment by nbari** [comment]
Hi, please find releases here: https://github.com/ssh-vault/ssh-vault/releases/tag/0.12.7
