### ISSUE TITLE
Website blocked in India

### ISSUE THREAD

**Issue by yuvipanda** [ssh-vault/ssh-vault#55]
ssh-vault is amazing software and I love it!

Unfortunately the Indian government is blocking access to https://ssh-vault.com/.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/30430/146820049-c9773969-2dcd-46d4-813b-ba4e66ffe011.png">

Not sure if there is anything you can do, but wanted to let you know.

GitHub isn't blocked so I can still access :)

**Comment by nbari** [comment]
Hi @yuvipanda, I updating the site, here is a preview, can you please check if this one is still blocked: https://ssh-vault.pages.dev/

**Comment by yuvipanda** [comment]
It is not! Yay?

**Comment by nbari** [comment]
Thanks for testing, will close this for now
