### ISSUE TITLE
use ssh-agent when asked for password

### ISSUE THREAD

**Issue by nbari** [ssh-vault/ssh-vault#6]
Find a way to use the ssh-agent to obtain the decrypted key in order to avoid typing the password every time a vault needs to be edited/viewed.  

Probably is not possible: http://security.stackexchange.com/a/55791/54143

**Comment by jsoriano** [comment]
Hi! I have been taking a look and indeed it doesn't seem possible :(
With ssh agent you don't have access to the private key or to encryption directives.

**Comment by nbari** [comment]
If I am right the ssh-agent keeps  the un-encrypted private key not the passphrase, but also I think is not that easy to retrieve private key.

In case ssh-agent could not be used, wondering how could keychain (mac os x) for example be used in a safe way, in last case is just a meter of typing password.

**Comment by jsoriano** [comment]
I think that keychains don't keep ssh private key passwords, they provide the ssh agent interface to ssh clients. At least this seems the case for gnome-keyring in Ubuntu.

**Comment by nbari** [comment]
Just updated to mac os Sierra and now not even ssh-agent working like before, for now I think is ok to close this.

**Comment by nbari** [comment]
This is now working, thanks to @tmaher  https://github.com/ssh-vault/ssh-vault/pull/12

**Comment by tmaher** [comment]
In Sierra, Apple annoyingly disabled auto-loading of keys, nominally to be more consistent with mainline OpenSSH. https://github.com/jirsbek/SSH-keys-in-macOS-Sierra-keychain/blob/master/README.md Is a good overview of the problem. To be clear, I'm using this on my own Sierra box, and keys with Keychain-backed passwords still load fine with `ssh-add -A`.

**Comment by nbari** [comment]
Hi @tmaher Just upgrade to macOS High Sierra and can't make this to work (avoid prompting for the password and read it from the keychain), it is working from your side?

**Comment by tmaher** [comment]
@nbari - yep, I've been on High Sierra on my personal box for a while, no major changes. What sort of errors are you getting?
