### ISSUE TITLE
 0.12.11 did not get marked as latest release

### ISSUE THREAD

**Issue by chenrui333** [ssh-vault/ssh-vault#63]
👋 it looks like 0.12.11 release did not get marked as latest release, also the default branch is still pointing to master branch, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/154092

**Comment by nbari** [comment]
Hi @chenrui333 many thanks for the heads up, I am testing the pipelines and need to update the homebrew formula since no I moved to `rust` any hints on this?

**Comment by nbari** [comment]
Hi @chenrui333 here a PR https://github.com/Homebrew/homebrew-core/pull/154122

**Comment by chenrui333** [comment]
Should be good now. Closing! Thanks @nbari! 🎉
