### ISSUE TITLE
Can't `view` the json it `create`s -- jq/string parse yourself

### ISSUE THREAD

**Issue by mcint** [ssh-vault/ssh-vault#66]
I see the file contents are in the json string. I seems easy enough to add this minimal parsing to the `view` command's behavior so tool can round-trip values it encrypts by itself.

`jq -r .vault doc.ssh-vault.json | ssh-vault v -k ssh_id`

**Comment by nbari** [comment]
Hi @mcint I am not getting it, can you please elaborate more?
