### ISSUE TITLE
help creating homebrew package

### ISSUE THREAD

**Issue by nbari** [ssh-vault/ssh-vault#7]
Need help to create a homebrew package in order to simplify the installation for Mac OS users.

**Comment by EspressoDan** [comment]
Hey! I'll take this if no one else is working on it currently

**Comment by nbari** [comment]
@EspressoDan would be great, thanks

**Comment by EspressoDan** [comment]
It looks like homebrew won't accept it because the repo is too new and isn't notable enough. They also would like a stable version for the formula. Sorry!

**Comment by nbari** [comment]
maybe the formula can be created and after repo/project becomes more notable/old/stable just use it

**Comment by postcert** [comment]
You can create a tap-repo though.
I set one up at https://github.com/postcert/homebrew-ssh-vault
You can simply run `brew tap postcert/ssh-vault` then `brew install ssh-vault` to install.

**Comment by nbari** [comment]
@postcert many thanks, just created https://github.com/ssh-vault/homebrew-tap, https://ssh-vault.com/post/homebrew/
