### ISSUE TITLE
test the windows binaries

### ISSUE THREAD

**Issue by nbari** [ssh-vault/ssh-vault#8]
Test the windows binaries https://dl.bintray.com/nbari/ssh-vault/ssh-vault_0.7.2_windows_amd64.zip

Check if creating, edit, viewing vaults works besides fetching the keys remotely or using keys locally.

**Comment by BhaveshSGupta** [comment]
@nbari The above link is not working!

**Comment by nbari** [comment]
@BhaveshSGupta please find the windows version here https://dl.bintray.com/nbari/ssh-vault/
the ":" I think is something use by bintray.

**Comment by nbari** [comment]
Just upload 0.7.3 please give a try here: https://dl.bintray.com/nbari/ssh-vault/ssh-vault_0.7.3_windows_amd64.zip  or here: https://dl.bintray.com/nbari/ssh-vault/ thanks.

**Comment by nbari** [comment]
@BhaveshSGupta I create a using your first key with fingerprint:

    b2:5b:33:86:ed:36:69:d2:c8:e7:8d:44:51:93:9e:46

```
SSH-VAULT;AES256;b2:5b:33:86:ed:36:69:d2:c8:e7:8d:44:51:93:9e:46
QXBAuP6lhBY5RREMxZl1Gi8XyXWAglNuS1B9OFL0V9L5yz3gqY2cADKw/unQucKR
c6Kq63TH/4rsE9iT2EJJAb0obJ2dM9IRdeJ2pY14GCncoPkEpodepiK+GWsUsoPj
HDNkVHBQXHSEb7Bgebv3cebTjeBi5AMgqxUxU3k8XGQtvIt/uHsYi2SlgyayEKI8
o4lSUlPzXGprfWrSC/b42ZBriDgZrfBIakEUqWNBQNzxgKQCKbVFUovF2qDzSjBp
4C62kNvfnI5nFHnrjtoHRJMKuTtSZPOMMYv/g+3g4880ghcTzj1pqQTTrXl5FX2J
VKLcRkyYElAsvZ4gpWmahA==;KA9j5E48xRE8goZK/OOG+uwJpiriwATO83V6fm+
6Jg9WajepIFwb8PynlFMDueXBq7EAbsCldQnD7dhf
```

For creating I used this:

    ssh-vault -u BhaveshSGupta create vault

In theory you should be available to see the content by doing 

    ssh-vault -k /path/to/your/key view file 

> file contains the previous encrypted data
